# Generates the minsol (手法A) cross-check fixture read by
# mss/tests/test_meddly_minsol.rs.
#
# Usage (the fixture is committed, so this is only needed to regenerate it):
#
#   cd <MDDMinsol checkout> && julia --project=. gen_minsol_fixture.jl <out.txt>
#
# No local libmeddly_c build is needed here -- unlike the MxD fixture, this uses
# no MEDDLY::CROSS, so the published libmeddly_c_jll is enough.
#
# For each system it records the FULL truth table of φ plus, for every level j,
# the minimal path vectors MPV(j) = minimal{x : φ(x) >= j}.
#
# Dumping the whole table matters: the Rust side rebuilds φ from it node by node
# rather than re-deriving it from the same formula, so the two implementations
# are compared on a function that is demonstrably identical rather than on one
# each side constructed for itself. Everything is in x-order (component index),
# not level order -- the two engines assign levels differently and minimal
# vectors must not depend on that.

using MDDMinsol, Meddly, Random

struct Case
    name::String
    sys::MDDMinsol.System
end

function build_cases()
    cs = Case[]
    push!(cs, Case("series3x3",   series_system(3; states=3)))
    push!(cs, Case("parallel3x3", parallel_system(3; states=3)))
    push!(cs, Case("kofn_2of3x3", kofn_system(2, 3; states=3)))
    push!(cs, Case("series4x2",   series_system(4; states=2)))
    push!(cs, Case("parallel2x4", parallel_system(2; states=4)))
    for seed in 1:4
        push!(cs, Case("rand333_s$seed",
                       random_monotone_system([3,3,3]; rng=MersenneTwister(seed))))
    end
    for seed in 1:3
        push!(cs, Case("rand232_s$seed",
                       random_monotone_system([2,3,2]; rng=MersenneTwister(100+seed))))
    end
    for seed in 1:2
        push!(cs, Case("rand2222_s$seed",
                       random_monotone_system([2,2,2,2]; rng=MersenneTwister(200+seed))))
    end
    cs
end

function main(path)
    Meddly.initialize()
    cases = build_cases()
    open(path, "w") do io
        println(io, "# generated by tools/gen_minsol_fixture.jl -- do not edit by hand")
        println(io, "# reference: MEDDLY via MDDMinsol.all_mpv_minsol (手法A, Rauzy Algorithm 3)")
        println(io, "# vectors are x-order (component index), values are absolute states")
        for c in cases
            sys = c.sys
            K = MDDMinsol.nvars(sys)
            doms = [length(sys.domains[i]) for i in 1:K]
            println(io, "case ", c.name)
            println(io, "domains ", join(doms, " "))
            println(io, "m ", sys.m)
            println(io, "coherent ", is_coherent(sys) ? "true" : "false")

            for s in Iterators.product((0:(d-1) for d in doms)...)
                v = eval_phi(sys, collect(s))
                println(io, "phi ", join(collect(s), " "), " ", v)
            end

            mpv = all_mpv_minsol(sys)
            for j in 1:(sys.m - 1)
                for x in mpv[j]
                    println(io, "mpv ", j, " ", join(x, " "))
                end
            end
            println(io, "end")
        end
    end
    println("wrote ", path, " (", length(cases), " cases)")
end

main(ARGS[1])
