# Generates the MEDDLY cross-check fixture read by mxdcore/tests/test_meddly.rs.
#
# Usage (the fixture is committed, so this is only needed to regenerate it):
#
#   MEDDLY_JL=~/path/to/Meddly.jl
#   cd $MEDDLY_JL && LIBMEDDLY_C_PATH=$MEDDLY_JL/c/libmeddly_c.dylib \
#       julia --project=. gen_meddly_fixture.jl <out.txt> <ncases> <seed>
#
# LIBMEDDLY_C_PATH must point at a LOCAL libmeddly_c build: MEDDLY::CROSS is not
# present in the published libmeddly_c_jll v0.5.0, so `cross` fails without one.
#
# The committed fixture was produced with ncases=25, seed=20260908.
#
# Membership is decided by intersecting with an explicit fully specified
# singleton and reading the cardinality, NOT by walking the diagram. Walking it
# would mean re-deriving MEDDLY's interleaved unprimed/primed layout and its
# identity reduction here -- exactly the semantics the cross-check exists to
# test independently -- so a bug there could agree with a bug in the Rust
# enumerator and hide both.

using Meddly
using Random

const DC = -1   # DONT_CARE
const DX = -2   # DONT_CHANGE

# level_sizes[k] is the size at level k (1-indexed), matching Domain(). The Rust
# side declares variables in the same order, so position i in every vector below
# means the same variable on both sides.
const DOMAINS = [2, 3, 2]

all_states(d) = collect(Iterators.product((0:(n-1) for n in d)...)) |> vec .|> collect

function main(path, ncases, seed)
    Meddly.initialize()
    rng = MersenneTwister(seed)
    states = all_states(DOMAINS)

    open(path, "w") do io
        println(io, "# generated by tools/gen_meddly_fixture.jl -- do not edit by hand")
        println(io, "# reference: MEDDLY via Meddly.jl, membership by singleton intersection")
        println(io, "domains ", join(DOMAINS, " "))

        for c in 0:(ncases-1)
            dom = Domain(copy(DOMAINS))
            sf  = MDDForestBool(dom)
            rf  = MDDForestBoolMxD(dom)

            println(io, "case ", c)

            # --- the relation: a union of singleton patterns, deliberately mixing
            # fully specified transitions with DONT_CARE / DONT_CHANGE components.
            rel = nothing
            for _ in 1:rand(rng, 1:4)
                u = Int[]; p = Int[]
                for (i, n) in enumerate(DOMAINS)
                    r = rand(rng)
                    if r < 0.35
                        push!(u, DC); push!(p, DX)          # invariant
                    elseif r < 0.55
                        push!(u, DC); push!(p, rand(rng, 0:(n-1)))
                    elseif r < 0.70
                        push!(u, rand(rng, 0:(n-1))); push!(p, DX)
                    else
                        push!(u, rand(rng, 0:(n-1))); push!(p, rand(rng, 0:(n-1)))
                    end
                end
                println(io, "singleton ", join(u, " "), " / ", join(p, " "))
                e = mxd_singleton(rf, u, p)
                rel = rel === nothing ? e : or(rel, e)
            end

            # --- lower and upper sets, as unions of set minterms with don't-cares.
            function gen_set(tag)
                acc = nothing
                for _ in 1:rand(rng, 1:3)
                    v = [rand(rng) < 0.3 ? DC : rand(rng, 0:(n-1)) for n in DOMAINS]
                    println(io, tag, " ", join(v, " "))
                    e = Edge(sf, v)
                    acc = acc === nothing ? e : or(acc, e)
                end
                acc
            end
            lower = gen_set("lower")
            upper = gen_set("upper")

            prod     = cross(lower, upper, rf)
            boundary = and(prod, rel)
            post     = post_image(lower, rel)
            pre      = pre_image(upper, rel)
            post_b   = post_image(lower, boundary)
            pre_b    = pre_image(upper, boundary)

            rels = ["rel" => rel, "cross" => prod, "boundary" => boundary]
            sets = ["lower" => lower, "upper" => upper, "post" => post,
                    "pre" => pre, "post_b" => post_b, "pre_b" => pre_b]

            for (name, e) in vcat(rels, sets)
                println(io, "card ", name, " ", Int(round(cardinality(e))))
            end

            # Membership, one probe per candidate.
            for (name, e) in rels
                for f in states, t in states
                    probe = mxd_singleton(rf, collect(f), collect(t))
                    if cardinality(and(e, probe)) > 0.5
                        println(io, "member ", name, " ", join(f, " "), " / ", join(t, " "))
                    end
                end
            end
            for (name, e) in sets
                for s in states
                    probe = Edge(sf, collect(s))
                    if cardinality(and(e, probe)) > 0.5
                        println(io, "member ", name, " ", join(s, " "))
                    end
                end
            end
            println(io, "end")
        end
    end
    println("wrote ", path)
end

main(ARGS[1], parse(Int, ARGS[2]), parse(Int, ARGS[3]))
